Search bar to add lecturers to course
InteIIigeNET/HwProj-2.0.1 pull request #111
Opened 2021-10-11 08:21 UTC by semtagg

2021-12-07 15:39 UTC, DedSec256 commented on HwProj.CoursesService/HwProj.CoursesService.API/Controllers/CoursesController.cs
> +        //[ProducesResponseType(typeof(AccountDataDto[]), (int)HttpStatusCode.OK)]
почему закомментированно?

2021-12-07 15:39 UTC, DedSec256 commented on HwProj.CoursesService/HwProj.CoursesService.API/Services/CoursesService.cs
> +        public async Task<AccountDataDto[]> GetLecturersAvailableForCourse(long courseId, string mentorId)
нет проверки на принадлежность ментора из запроса к курсу

2021-12-07 15:39 UTC, DedSec256 commented on HwProj.CoursesService/HwProj.CoursesService.API/Services/CoursesService.cs
> +            var mentorIds = (await GetAsync(courseId, mentorId)).MentorIds.Split('/').ToList();
лучше вынести получение списка менторов курса в утилиту

2022-01-28 12:41 UTC, semtagg commented on HwProj.CoursesService/HwProj.CoursesService.API/Services/CoursesService.cs
> +        public async Task<AccountDataDto[]> GetLecturersAvailableForCourse(long courseId, string mentorId)
> нет проверки на принадлежность ментора из запроса к курсу

@DedSec256 а это точно нужно?

2022-03-19 14:22 UTC, DedSec256 requested changes

2022-03-19 14:22 UTC, DedSec256 commented on HwProj.CoursesService/HwProj.CoursesService.API/Services/CoursesService.cs
> +            ;
?

2022-03-19 14:22 UTC, DedSec256 commented on HwProj.CoursesService/HwProj.CoursesService.Client/CoursesServiceClient.cs
> +            return await response.DeserializeAsync<AccountDataDto[]>().ConfigureAwait(false);
.ConfigureAwait(false) можно не писать -- ASP.NET Core работает без контекстов синхронизации

2022-03-19 14:22 UTC, DedSec256 commented on HwProj.CoursesService/HwProj.CoursesService.API/Services/CoursesService.cs
> +                    await RejectCourseMateAsync(courseId, userId);
это точно то, что должно вызываться? Похоже на какой-то костыль

2022-03-19 14:22 UTC, DedSec256 commented on HwProj.CoursesService/HwProj.CoursesService.Client/CoursesServiceClient.cs
> +        public async Task<AccountDataDto[]> GetLecturersAvailableForCourse(long courseId, string mentorId)
разделитель потерялся

2022-03-19 14:22 UTC, DedSec256 commented on HwProj.APIGateway/HwProj.APIGateway.API/Controllers/CoursesController.cs
> +            var result = await _coursesClient.GetLecturersAvailableForCourse(courseId, mentorId);
было бы неплохо автоматически прокидывать userId из запроса, как это делается в других аналогичных местах
https://github.com/InteIIigeNET/HwProj-2.0.1/blob/master/HwProj.CoursesService/HwProj.CoursesService.Client/CoursesServiceClient.cs#L95

2022-03-19 14:22 UTC, DedSec256 commented on HwProj.Common/HwProj.Utils/CommonExtensions.cs
> +        public static List<string> GetMentorIds(this string line)
в PR про CourseMentorOnlyAttribute эта логика уже есть в сервисе

2022-04-06 02:01 UTC, DedSec256 approved these changes

2022-04-08 22:02 UTC, merged