Notifications categories
InteIIigeNET/HwProj-2.0.1 pull request #125
Opened 2021-11-09 20:56 UTC by ElenaBakova

2022-05-15 21:26 UTC, DedSec256 requested changes
Некоторые замечания

2022-05-15 21:26 UTC, DedSec256 commented on HwProj.NotificationsService/HwProj.NotificationsService.API/AutomapperProfile.cs
> +﻿using System.Diagnostics;
лишний юзинг

2022-05-15 21:26 UTC, DedSec256 commented on HwProj.NotificationsService/HwProj.NotificationsService.API/Controllers/NotificationsController.cs
> +            return Ok(groupedNotifications ?? new CategorizedNotifications[] { });
Array.Empty<CategorizedNotifications>

2022-05-15 21:26 UTC, DedSec256 commented on HwProj.NotificationsService/HwProj.NotificationsService.API/Services/INotificationsService.cs
> +        CategorizedNotifications[] GroupAsync(Notification[] notifications);
если метод не Async, то просто Group

2022-05-15 21:26 UTC, DedSec256 commented on HwProj.NotificationsService/HwProj.NotificationsService.API/Services/INotificationsService.cs
>      public interface INotificationsService
Этот интерфейс более вообще не нужен, раз уж мы используем подход домена.

2022-05-15 21:26 UTC, DedSec256 commented on HwProj.NotificationsService/HwProj.NotificationsService.API/Services/NotificationsDomain.cs
> +        public async Task<long> AddNotificationAsync(Notification notification)
Этот метод можно использовать сразу из репозитория, в домене он не нужен

2022-05-15 21:26 UTC, DedSec256 commented on HwProj.NotificationsService/HwProj.NotificationsService.API/Services/NotificationsDomain.cs
> +        public NotificationsDomain(INotificationsRepository repository, IMapper mapper)
Принимать репозиторий тут тоже не нужно тогда

2022-05-15 21:26 UTC, DedSec256 commented on HwProj.NotificationsService/HwProj.NotificationsService.API/Services/NotificationsDomain.cs
> +        public async Task MarkAsSeenAsync(string userId, long[] notificationIds)
этот метод тоже в домене не нужен

2022-05-15 21:26 UTC, DedSec256 commented on HwProj.NotificationsService/HwProj.NotificationsService.API/Repositories/NotificationsRepository.cs
> -            if (filter.HasSeen != null)
если сейчас фильтр вообще нигде не используется, мб удалим вообще его отсюда?

2022-05-15 21:26 UTC, DedSec256 commented on hwproj.front/src/components/AppBar.tsx
> -                                    Профиль
Я правильно понимаю, что профиль вообще пропал?

2022-05-17 18:52 UTC, ElenaBakova commented on hwproj.front/src/components/AppBar.tsx
> -                                    Профиль
Ну пока да, я могу его добавить, но там просто пустая страница будет же

2022-05-17 21:55 UTC, DedSec256 requested changes

2022-05-17 21:55 UTC, DedSec256 commented on hwproj.front/src/App.tsx
> +                <Route exact path="/notifications/:id" component={Notifications}/>
Точно ли должен присутствовать такой маршрут для уведомлений?

2022-05-17 21:55 UTC, DedSec256 commented on hwproj.front/src/components/Notifications.tsx
> +            if (item != null && item.seenNotifications != undefined)
```suggestion
            if (item && item.seenNotifications)
```

2022-05-17 21:55 UTC, DedSec256 commented on hwproj.front/src/components/Notifications.tsx
> +            if (item != null && item.notSeenNotifications != undefined)
```suggestion
            if (item && item.notSeenNotifications)
```

2022-05-17 21:55 UTC, DedSec256 commented on hwproj.front/src/components/Notifications.tsx
> +            <p>Loading...</p>
Может, лучше на русском, как в остальных частях сервиса? (:

2022-05-17 21:55 UTC, DedSec256 commented on hwproj.front/src/components/Notifications.tsx
> +    isCheckAll: boolean;
нужно как-то более понятно переименовать, возможно, showAll

2022-05-17 21:55 UTC, DedSec256 commented on hwproj.front/src/components/Notifications.tsx
> +
с ростом числа уведомлений этот код будет работать все медленнее. Я бы ожидал передачу callback с изменением состояния нужного уведомления, тогда не пришлось бы фильтровать весь список, по нажатию уведомление само обновило бы себя

2022-05-17 21:59 UTC, DedSec256 commented on hwproj.front/src/components/Notifications.tsx
> +const Profile: FC<RouteComponentProps<IProfileProps>> = (props) => {
это уже не Profile (:

Предлагаю вот что сделать: на изменения всех галочек и категорий в колбэках лишь изменять стейт фильтра. Затем сделать одну функцию, которая будет на основе фильтров и галочек считать уведомления для отображения.

2022-09-04 17:44 UTC, merged