Change connection string
InteIIigeNET/HwProj-2.0.1 pull request #129
Opened 2021-11-11 12:06 UTC by Volodya-Petrov

2021-11-11 20:25 UTC, semtagg commented
bruh...
![image](https://user-images.githubusercontent.com/76883458/141364135-097d5ab6-0ba4-4843-b4bb-9b2759070f7f.png)

2021-11-19 08:31 UTC, semtagg commented
bruh..
![image](https://user-images.githubusercontent.com/76883458/142590840-52d89f48-335c-446a-8710-3c111e25ffc1.png)

2021-11-19 08:41 UTC, semtagg approved these changes
Вроде работает!

2021-11-19 09:21 UTC, DedSec256 requested changes
Изменение версии языка лучше вынести в отдельный PR. Так же общую часть конфигурирования лучше вынести в HwProj.Common

2021-11-19 09:21 UTC, DedSec256 commented on HwProj.AuthService/HwProj.AuthService.API/Startup.cs
> +            var connectionString =Configuration.GetConnectionString("DefaultConnectionForWindows");
Думаю, это можно вынести в HwProj.Common

2021-11-19 09:31 UTC, semtagg commented on HwProj.AuthService/HwProj.AuthService.API/Startup.cs
> +            var connectionString =Configuration.GetConnectionString("DefaultConnectionForWindows");
и пробел добавить надо бы, после =

2021-11-19 16:01 UTC, DedSec256 commented on HwProj.SolutionsService/HwProj.SolutionsService.API/Startup.cs
> +using System.Runtime.InteropServices;
это точно тут нужно?

2021-11-19 16:01 UTC, DedSec256 commented on HwProj.EventBus/HwProj.EventBus.Client/HwProj.EventBus.Client.csproj
> +    <LangVersion>preview</LangVersion>
осталось ещё одно место (:

2021-11-19 16:01 UTC, DedSec256 commented on HwProj.CoursesService/HwProj.CoursesService.API/Startup.cs
> +        {
отформатировать файл

2021-11-19 16:01 UTC, DedSec256 commented on HwProj.AuthService/HwProj.AuthService.API/Startup.cs
> +﻿using System.Runtime.InteropServices;
точно эти юзинги не лишние?

2021-11-20 10:08 UTC, merged