[WIP] AuthService Integration Tests
InteIIigeNET/HwProj-2.0.1 pull request #148
Opened 2022-04-29 17:47 UTC by semtagg

2022-05-10 22:29 UTC, DedSec256 requested changes

2022-05-10 22:29 UTC, DedSec256 commented on HwProj.AuthService/HwProj.AuthService.Client/AuthServiceClient.cs
> +            return user.Id;
Добавлен бан! Если юзер будет не найден, здесь выпадет NullReferenceException

2022-05-10 22:29 UTC, DedSec256 commented on HwProj.AuthService/HwProj.AuthService.IntegrationTests/AuthServiceTests.cs
> +        /*public static IEnumerable<object[]> DummyGoogleRegisterData()
Закомментированный код лучше удалить.

2022-05-10 22:29 UTC, DedSec256 commented on HwProj.AuthService/HwProj.AuthService.IntegrationTests/AuthServiceTests.cs
> +        [TestCaseSource(nameof(DummyRegisterData))]
Здесь точно нужен TestCaseSource? Тесткейс сам не поменяется, только случайно сгенерированные данные.

2022-05-10 22:29 UTC, DedSec256 commented on HwProj.AuthService/HwProj.AuthService.IntegrationTests/AuthServiceTests.cs
> +            resultData.Name.Should().Be(userData.Name);
лучше сравнить Should.Be(new UserData ...)

2022-05-10 22:29 UTC, DedSec256 commented on HwProj.AuthService/HwProj.AuthService.IntegrationTests/AuthServiceTests.cs
> +        public async Task TestEditPassword(RegisterViewModel userData)
Нужно проверить, что после изменения пароля все ещё можно зайти в сервис

2022-05-10 22:29 UTC, DedSec256 commented on HwProj.AuthService/HwProj.AuthService.IntegrationTests/AuthServiceTests.cs
> +            resultData.Errors.IsNullOrEmpty().Should().BeTrue();
нужно проверить, что роль действительно поменяется

2022-05-10 22:29 UTC, DedSec256 commented on HwProj.AuthService/HwProj.AuthService.IntegrationTests/AuthServiceTests.cs
> +        public async Task TestGetAllLecturers(RegisterViewModel userData)
Здесь аналогично с TestGetAllStudents. Ещё нужно не забыть поменять роли у юзеров.

2022-05-10 22:29 UTC, DedSec256 commented on HwProj.AuthService/HwProj.AuthService.IntegrationTests/AuthServiceTests.cs
> +        public async Task TestGetAllStudents(RegisterViewModel userData)
Здесь было бы хорошо создать пару юзеров и проверить, что они есть в списке всех юзеров. И, конечно же, оставить комментарий, почему проверяется именно нахождение в списке всех студентов, а не полное совпадение.

2022-05-10 22:29 UTC, DedSec256 commented on HwProj.AuthService/HwProj.AuthService.IntegrationTests/AuthServiceTests.cs
> +    public class Tests
Было бы хорошо ещё добавить тест на GetAccountData

2022-05-13 16:17 UTC, DedSec256 commented on HwProj.AuthService/HwProj.AuthService.IntegrationTests/AuthServiceTests.cs
> +            result.Errors.Should().BeNullOrEmpty();
Было бы неплохо добавить текст ошибки для такого запроса

2022-05-13 16:19 UTC, DedSec256 commented on HwProj.AuthService/HwProj.AuthService.IntegrationTests/AuthServiceTests.cs
> +            result.Should().BeNull();
здесь бы что-нибудь нормальное возвращать

2022-05-13 16:20 UTC, DedSec256 requested changes
Отформатируй, пожалуйста, и удали закомментированный код.

2022-05-13 16:44 UTC, semtagg commented on HwProj.AuthService/HwProj.AuthService.IntegrationTests/AuthServiceTests.cs
> +            claims[3].Value.Should().Be(Roles.StudentRole);
добавить сравнение id

2022-05-13 16:51 UTC, merged

2022-05-13 16:51 UTC, DedSec256 commented
Спасибо!