Расширенная статистика студентов
InteIIigeNET/HwProj-2.0.1 pull request #378
Opened 2024-04-20 09:26 UTC by Artem-Rzhankoff

2024-04-21 17:03 UTC, DedSec256 commented on HwProj.SolutionsService/HwProj.SolutionsService.API/Services/SolutionsService.cs
> +            solution.RatingDate = DateTime.UtcNow;
лучше вынести в локальную переменную и использовать одинаковое время

2024-04-27 18:28 UTC, DedSec256 requested changes

2024-04-27 18:28 UTC, DedSec256 commented on HwProj.CoursesService/HwProj.CoursesService.API/Migrations/CourseContextModelSnapshot.cs
> -
вот эти изменения не нужны

2024-04-27 18:28 UTC, DedSec256 commented on HwProj.CoursesService/HwProj.CoursesService.API/Services/CoursesService.cs
> +
лишний пробел

2024-04-27 18:28 UTC, DedSec256 commented on HwProj.APIGateway/HwProj.APIGateway.API/Models/Statistics/StatisticsCourseAdvancedViewModel.cs
> +        public StatisticsCourseMatesModel[] Students { get; set; }
```suggestion
        public StatisticsCourseMatesModel[] StudentStatistics { get; set; }
```

2024-04-27 18:28 UTC, DedSec256 commented on HwProj.SolutionsService/HwProj.SolutionsService.Client/ISolutionsServiceClient.cs
> +        Task<StatisticsCourseAdvancedDto> GetAdvancedStatistics(long courseId);
переименовал бы более осмысленно, ближе к статистике успеваемости

2024-04-27 18:28 UTC, DedSec256 commented on HwProj.SolutionsService/HwProj.SolutionsService.Client/SolutionsServiceClient.cs
> +                _solutionServiceUri + $"api/Solutions/getAdvancedStat/{courseId}");
путь бы поправил после переименования

2024-04-27 18:28 UTC, DedSec256 commented on hwproj.front/src/App.tsx
> +                    <Route path="statistics/:courseId/charts" element={<StudentStatsChart/>}/> // можно чекать через апишку
отрендерится как текст, комментарии в tsx пишутся иначе

2024-04-27 18:28 UTC, DedSec256 commented on HwProj.SolutionsService/HwProj.SolutionsService.API/Controllers/SolutionsController.cs
> +                }).ToArray();
```suggestion
            var bestStudentSolutions = course.Homeworks
                .SelectMany(e => e.Tasks)
                .Select(task=> new StatisticsCourseMeasureSolutionModel {
                        TaskId = task.Id,
                        Rating = task.MaxRating,
                        PublicationDate = task.PublicationDate})
                .ToArray();
```

2024-04-27 18:28 UTC, DedSec256 commented on HwProj.SolutionsService/HwProj.SolutionsService.API/Controllers/SolutionsController.cs
> +                .GroupBy(e => new { e.StudentId, e.TaskId })
```suggestion
                .GroupBy(e => new { Id: e.GroupId is {} groupId ? groupId.ToString() : e.StudentId, e.TaskId })
```

2024-04-27 18:28 UTC, DedSec256 commented on HwProj.SolutionsService/HwProj.SolutionsService.API/Controllers/SolutionsController.cs
> +                .Select(e => e.OrderByDescending(s => s.PublicationDate).First())
```suggestion
                .Select(e => e.OrderByDescending(s => s.PublicationDate).FirstOrDefault(s => s.Status != Posted))
```

2024-04-27 18:28 UTC, DedSec256 commented on HwProj.SolutionsService/HwProj.SolutionsService.API/Controllers/SolutionsController.cs
> +                    TaskId = e.Select(t => t.TaskId).First(),
```suggestion
                    TaskId = e.Key,
```

2024-04-27 18:28 UTC, DedSec256 commented on HwProj.SolutionsService/HwProj.SolutionsService.API/Controllers/SolutionsController.cs
> +                    Rating = e.Sum(s => s.Rating) / (double)course.CourseMates.Length,
```suggestion
                    Rating = e.Sum(s => s.Rating) / (double)e.Count(),
```

2024-04-27 18:28 UTC, DedSec256 commented on HwProj.SolutionsService/HwProj.SolutionsService.API/Controllers/SolutionsController.cs
> +                    Rating = e.Sum(s => s.Rating) / (double)course.CourseMates.Length,
Ещё можно оставить здесь комментарий

2024-04-27 18:38 UTC, AlexPoziev commented on HwProj.SolutionsService/HwProj.SolutionsService.API/Controllers/SolutionsController.cs
> +                .GroupBy(e => new { e.StudentId, e.TaskId })
Если честно, сколько раз вижу is {} столько же раз гуглю, чтобы убедиться. что это проверка на null :)
Кажется, что e.GroupdId != null в разы читабельней

2024-04-27 18:41 UTC, DedSec256 commented on hwproj.front/src/components/Courses/StudentStats.tsx
> +        navigate(`../../../statistics/${courseId}/charts`, {relative: 'path'})
лучше в ссылках не использовать ../../

2024-04-27 18:41 UTC, DedSec256 commented on hwproj.front/src/components/Courses/Statistics/StudentStatsTooltip.tsx
> +const StudentStatsTooltip : React.FC<IDummyInterface> = (props) => {
можно создать на основе Material UI Tooltip

2024-04-27 18:41 UTC, DedSec256 commented on hwproj.front/src/components/Courses/Statistics/HelpPopoverChartInfo.tsx
> +﻿import React, {useRef, useState} from 'react';
аналогично, вероятно, можно заменить на material ui tooltip

2024-04-27 18:41 UTC, DedSec256 commented on hwproj.front/src/components/Courses/Statistics/StudentCheckboxList.tsx
> +    onStudentSelection : (studentId : string) => void;
```suggestion
    onStudentsChange : (studentIds : string[]) => void;
```

2024-04-27 18:41 UTC, DedSec256 commented on hwproj.front/src/components/Courses/Statistics/StudentCheckboxList.tsx
> +                newSelectChangedStudents.forEach(s => props.onStudentSelection(s));
не нужно

2024-04-27 18:42 UTC, DedSec256 commented on hwproj.front/src/components/Courses/StudentStats.tsx
> +export const MyDataContext = createContext(null);
это точно нужно?

2024-05-27 01:25 UTC, closed without merging