Интеграция HwProj c университетской базой
InteIIigeNET/HwProj-2.0.1 pull request #470
Opened 2024-12-12 19:39 UTC by Salvatore112

Было сделано:

- Реализована функциональность по получению образовательных программ, учебных групп
и информации о студентах по LDAP

2025-03-16 16:36 UTC, Salvatore112 commented
Разобрался в конфигурации и вынес туда логин с паролем для служебного аккаунта

2025-03-18 19:36 UTC, YuriUfimtsev requested changes

2025-03-18 19:36 UTC, YuriUfimtsev commented on HwProj.APIGateway/HwProj.APIGateway.API/Controllers/CoursesController.cs
> +                studentsIDs.Add(studentId);
Можно оптимизировать и упростить, используя LINQ

1. Получить все id студентов одним запросом к AuthServiceClient
2. С помощью Where и Select linq смаппить нужное в RegisterViewModel
3. После этого с помощью TPL распараллелить запросы регистрации студентов и дождаться через Task.WaitAll

2025-03-18 19:36 UTC, YuriUfimtsev commented on HwProj.APIGateway/HwProj.APIGateway.API/Controllers/CoursesController.cs
> +                    registerModel.Password = "123456";
Предлагаю вынести в appsettings

2025-03-18 19:36 UTC, YuriUfimtsev commented on HwProj.Common/HwProj.Models/CoursesService/ViewModels/CourseViewModels.cs
> +        public List<string> studentIDs { get; set; }
```suggestion
        public List<string> studentIDs { get; set; } = new List<string>();
```

2025-03-18 19:36 UTC, YuriUfimtsev commented on HwProj.CoursesService/HwProj.CoursesService.API/Controllers/CoursesController.cs
> +
Аналогично, можно оптимизировать и упростить, используя LINQ.
Пока это очень неоптимально, учитывая, что каждый AcceptCourseMateAsync и AddStudentAsync первой строкой запрашивают из репозитория один и тот же курс.
Можно в _coursesService новый метод добавить

2025-03-18 19:36 UTC, YuriUfimtsev commented on HwProj.AuthService/HwProj.AuthService.API/Controllers/AccountController.cs
> +            await RequestPasswordRecovery(passwordRecoveryModel);
Это ведь нужно только для студентов, зарегистрированных при создании нового курса. 
На регистрацию других это не должно влиять

2025-03-18 19:36 UTC, YuriUfimtsev commented on HwProj.APIGateway/HwProj.APIGateway.API/Controllers/CoursesController.cs
> +                studentsIDs.Add(studentId);
Кстати, поскольку процесс небыстрый, надо на фронтенде не забыть добавить элемент загрузки: с помощью LoadingButton или LoadingButton и дополнительного уведомления

2025-03-18 21:23 UTC, YuriUfimtsev commented on HwProj.AuthService/HwProj.AuthService.API/Controllers/AccountController.cs
> +            await RequestPasswordRecovery(passwordRecoveryModel);
Ещё, пожалуйста, выполни rebase, чтобы конфликты исправить. И сделай для проектов отдельную папку. Например, HwProj.StudentsInfo

2025-03-25 18:20 UTC, Salvatore112 commented on HwProj.APIGateway/HwProj.APIGateway.API/Controllers/CoursesController.cs
> +            var students = _studentsInfo.GetStudentInformation(model.GroupName);
И здесь, и на фронтенде это уже предусмотрено. Проверил ещё раз, произвольные курсы создаются

2025-03-25 20:19 UTC, Salvatore112 commented on HwProj.AuthService/HwProj.AuthService.API/Controllers/AccountController.cs
> +            await RequestPasswordRecovery(passwordRecoveryModel);
> Это ведь нужно только для студентов, зарегистрированных при создании нового курса. На регистрацию других это не должно влиять

В прошлом семестре решили, что можно и для всех сделать, и в будущих планах планируется переделать текущую регистрацию. Думаю, на созвоне можно будет это обсудить

2025-03-25 20:54 UTC, YuriUfimtsev commented on HwProj.APIGateway/HwProj.APIGateway.API/Controllers/CoursesController.cs
> +            var students = _studentsInfo.GetStudentInformation(model.GroupName);
Не хочется даже соединение с LDAP создавать, если заведомо знаем, что курс новый.
```suggestion
            if !(string.IsNullOrEmpty(model.GroupName))
            {
                var students = _studentsInfo.GetStudentsInformation(model.GroupName);
```

2025-04-01 19:10 UTC, DedSec256 commented on HwProj.APIGateway/HwProj.APIGateway.API/Controllers/CoursesController.cs
> +        public  IActionResult GetGroups(string programName)
Ограничение по роли Лектора добавить

2025-04-01 19:10 UTC, DedSec256 commented on HwProj.APIGateway/HwProj.APIGateway.API/Controllers/CoursesController.cs
> +        [ProducesResponseType(typeof(List<ProgramModel>), (int)HttpStatusCode.OK)]
Добавить ограничение по роли Лектора

2025-04-01 19:12 UTC, DedSec256 commented on Hwproj.StudentInfo/StudentsInfo/StudentsInformation.cs
> +                connection.Connect(_ldapHost, _ldapPort);
есть ли ConnectAsync?

2025-04-01 19:13 UTC, DedSec256 commented on HwProj.AuthService/HwProj.AuthService.API/Controllers/AccountController.cs
> +            await RequestPasswordRecovery(passwordRecoveryModel);
Давай здесь напишем похожую логику, только для подтверждения почты. + Добавит новое событие и обработчик в NotificationsService

2025-04-06 21:42 UTC, Salvatore112 commented on Hwproj.StudentInfo/StudentsInfo/StudentsInformation.cs
> +                var results = connection.Search(
SearchAsync нету, только Search

2025-04-06 21:42 UTC, Salvatore112 commented on Hwproj.StudentInfo/StudentsInfo/StudentsInformation.cs
> +                connection.Connect(_ldapHost, _ldapPort);
ConnectAsync нету, только Connect

2025-04-06 21:43 UTC, Salvatore112 commented on Hwproj.StudentInfo/StudentsInfo/StudentsInformation.cs
> +                var connection = new LdapConnection();
Глянул, нет, он не IDisposable

2025-04-07 21:33 UTC, Salvatore112 commented on HwProj.AuthService/HwProj.AuthService.API/Controllers/AccountController.cs
> +            await RequestPasswordRecovery(passwordRecoveryModel);
Т.к это уже сделали на прошлой неделе, я тут просто код с восстановлением пароля уберу

2025-04-08 20:35 UTC, Salvatore112 commented on HwProj.APIGateway/HwProj.APIGateway.API/Controllers/CoursesController.cs
> +                    await AuthServiceClient.Register(registerModel);
Сейчас ещё раз пробежался глазами, тут действительно это нужно? Просто, регистрация уже оптимизирована с помощью LINQ и распараллелена (Юрий выше оставлял комментарий по этому поводу)

2025-04-08 21:38 UTC, DedSec256 commented on HwProj.APIGateway/HwProj.APIGateway.API/Controllers/CoursesController.cs
> +                    await AuthServiceClient.Register(registerModel);
Да, идея в том, чтобы не делать 10 однотипных запросов по сети, а сделать один, в котором передать пачку данных.

2025-04-10 22:38 UTC, DedSec256 commented
Можешь, пожалуйста, отребейзить изменения?

2025-04-10 23:25 UTC, Salvatore112 commented
> Можешь, пожалуйста, отребейзить изменения?

Собирался как раз, там просто небольшой баг в sln-ке обнаружился, который я пофиксил + страничку с созданием курса полностью переделали, вот сейчас думаю, как подружить мой фронт с текущим

2025-04-11 01:25 UTC, Salvatore112 commented
> Можешь, пожалуйста, отребейзить изменения?

Готово, и как назло опять вайфай лег, так что LDAP пока для меня закрыт..

2025-04-11 20:52 UTC, Salvatore112 commented
Думаю, можно уже померджить, замечания я поправил @YuriUfimtsev @DedSec256

2025-04-22 00:17 UTC, DedSec256 approved these changes

2025-04-22 00:17 UTC, DedSec256 commented
Круто, спасибо!

2025-04-22 00:17 UTC, merged