Обновление редактора Markdown в сервисе
InteIIigeNET/HwProj-2.0.1 pull request #471
Opened 2024-12-14 14:10 UTC by YuriUfimtsev

1. **Обновлена версия nodejs** (до 16.12.0) (что повлекло множество обновлений в package-lock.json).

2. **Обновлены версии react** (до 17.0.2) **и** связанных mui-**библиотек стилей**

3. **Обновлён редактор Markdown** во всех местах использования: комментирование решения со стороны преподавателя и студента, создание, редактирование задач и домашних работ, создание вопросов и ответов. Также в соответствующих местах обновлен компонент markdown-preview, отвечающий за рендеринг markdown.
- В новом редакторе также реализовал локализацию вспомогательного текста (появляется при наведении на кнопки тулбара), подключил в качестве плагина rehype-sanitize для защиты от XSS.

- Сохранены стили предыдущей версии preview сервиса: шрифт, размер и т.д. Для этого повторил существующие стили (MarkdownEditor.css)

- Несколько примеров отображения нового редактора:

2024-12-14 23:10 UTC, DedSec256 requested changes

2024-12-14 23:10 UTC, DedSec256 commented on hwproj.front/src/components/Courses/CourseExperimental.tsx
> +                    textColor="inherit"
можем сделать это значениями по умолчанию?

2024-12-14 23:10 UTC, DedSec256 commented on hwproj.front/src/components/Courses/CourseFilter.tsx
> -
это точно нужно в этом PR?

2024-12-14 23:10 UTC, DedSec256 commented on hwproj.front/src/components/Courses/AddLecturerInCourse.tsx
> +        if (!ValidationUtils.isCorrectEmail(lecturerState.email)) {
надо отребейзиться, видимо?

2024-12-15 00:00 UTC, YuriUfimtsev commented on hwproj.front/src/components/Courses/AddLecturerInCourse.tsx
> +        if (!ValidationUtils.isCorrectEmail(lecturerState.email)) {
надо будет в мастере поправить )

2024-12-15 01:10 UTC, YuriUfimtsev commented
Разработка продолжена в пул-реквестах #472 и #473

2024-12-15 01:10 UTC, closed without merging