E mail and bot
InteIIigeNET/HwProj-2.0.1 pull request #97
Opened 2021-09-16 17:57 UTC by MikePuzanov

E-mail only

2021-09-16 18:07 UTC, semtagg reviewed
Молодец Миша, хорошо поработал!

2021-09-16 18:28 UTC, DedSec256 commented
![image](https://user-images.githubusercontent.com/26364714/133665505-4485a661-2eb4-4882-a17b-6f64f767beb1.png)
эти коммиты точно должны быть тут? (:

2021-09-16 22:34 UTC, DedSec256 requested changes
Спасибо за PR! Есть некоторые небольшие замечания.

2021-09-16 22:34 UTC, DedSec256 commented on HwProj.CoursesService/HwProj.CoursesService.API/Events/LecturerAcceptToCourseEvent.cs
> +        public AccountDataDto Student { get; set; }
нам точно тут прям AccountDataDto нужно?

2021-09-16 22:34 UTC, DedSec256 commented on HwProj.CoursesService/HwProj.CoursesService.API/Events/LecturerRejectToCourseEvent.cs
> +using HwProj.Models.AuthService.DTO;
кажется, это лишнее изменение

2021-09-16 22:34 UTC, DedSec256 commented on HwProj.CoursesService/HwProj.CoursesService.API/Services/CoursesService.cs
> +
вернуть, как было (:

2021-09-16 22:34 UTC, DedSec256 commented on HwProj.NotificationsService/HwProj.NotificationsService.API/Controllers/NotificationsController.cs
> +
если этот код не нужен, то его лучше удалить

2021-09-16 22:34 UTC, DedSec256 commented on HwProj.NotificationsService/HwProj.NotificationsService.API/EventHandlers/EditProfileEventHandler.cs
> +        public EditProfileEventHandler(INotificationsRepository notificationRepository, INotificationsService notificationsService, IMapper mapper, IAuthServiceClient authServiceClient)
тут бы файл отформатировать целиком...

2021-09-16 22:34 UTC, DedSec256 commented on HwProj.NotificationsService/HwProj.NotificationsService.API/EventHandlers/EditProfileEventHandler.cs
>  }
лучше ньюлайны оставлять

2021-09-16 22:34 UTC, DedSec256 commented on HwProj.NotificationsService/HwProj.NotificationsService.API/EventHandlers/LecturerAcceptToCourseEventHandler.cs
> +                Body = $"Вас приняли на курс <a href='http://localhost:3000/courses/{@event.CourseId}'>{@event.CourseName}</a>.",
вот это бы вынести куда-то в конфиги, замучаемся потом менять url на нормальный домен

2021-09-16 22:34 UTC, DedSec256 commented on HwProj.NotificationsService/HwProj.NotificationsService.API/EventHandlers/UpdateHomeworkEventHandler.cs
> +                    Category = "Домашние задания",
категории лучше в виде Enum

2021-09-16 22:34 UTC, DedSec256 commented on HwProj.NotificationsService/HwProj.NotificationsService.API/Services/NotificationsService.cs
> +            using (var client = new MailKit.Net.Smtp.SmtpClient())
а нельзя его один раз подключить и использовать потом?

2021-09-16 22:34 UTC, DedSec256 commented on HwProj.NotificationsService/HwProj.NotificationsService.API/Services/NotificationsService.cs
> +                await client.AuthenticateAsync("testhwproj@gmail.com", "HwProj-2.0.1");
это всё тоже было бы неплохо в конфиг вынести

2021-09-17 15:59 UTC, semtagg reviewed
Михаил, а будет ли возможность отписаться от рассылки?

2022-09-11 06:40 UTC, DedSec256 commented
Кажется, уже неактуально! Спасибо за работу (:

2022-09-11 06:40 UTC, closed without merging